[package]
name = "tictactoe"
version = "0.1.0"
authors = ["Robert <sk.robchik@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adversarial_search = { path = "../adversarial_search" }